name: WeatherBot

on:
  schedule:
    - cron: '0 14 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
    - name: Run a multi-line script
      run: |
        WTTR=$(curl -s "https://wttr.in/Houston?format=%l:+%c+%t")
        curl -s -H 'Content-Type: application/json' -d '{"text": "'"Good morning from GitHub Actions.\n\n$WTTR\n\nHave a great day."'"}' ${{ secrets.WEBHOOK_URL }}
